import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import TVNoise from "@/components/tv-noise";
import { ModeProvider } from "@/context/mode";
import { ModeSwitcher } from "@/components/mode-switcher";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ModeProvider defaultMode="realistic" storageKey="ui-mode">
          <div
            className="min-h-screen  text-foreground font-sans flex items-center justify-center p-4 md:p-8"
            style={{
              backgroundImage: "url(/images/background.jpg)",
              backgroundSize: "cover",
              backgroundPosition: "center",
            }}
          >
            <TVNoise opacity={1} intensity={0.2} speed={40} />
            <div className="w-full max-w-225 z-50 aspect-[1.6/1] bg-[#222] relative p-4 rounded-2xl border  overflow-hidden flex  shadow-[inset_0_1px_rgb(255_255_255/0.15)]">{children}</div>
          </div>
          <ModeSwitcher />
        </ModeProvider>
      </body>
    </html>
  );
}
