import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import TVNoise from "@/components/tv-noise";
import { ModeProvider } from "@/context/mode";
import { ModeSwitcher } from "@/components/mode-switcher";
import "./globals.css";
import { cn } from "@/lib/utils";
import { GlassEffect } from "@/components/glass-effect";
import { useMode } from "@/context/mode";
import { MainContent } from "@/components/main-content";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${geistMono.variable} font-geist-mono antialiased`}>
        <ModeProvider defaultMode="realistic" storageKey="ui-mode">
          <main
            className="min-h-screen text-foreground font-mono flex items-center justify-center p-4 md:p-8"
            style={{
              backgroundImage: "url(/images/background.jpg)",
              backgroundSize: "cover",
              backgroundPosition: "center",
            }}
          >
            <TVNoise opacity={1} intensity={0.2} speed={40} />
            <MainContent>{children}</MainContent>
          </main>
          <ModeSwitcher />
        </ModeProvider>
      </body>
    </html>
  );
}
