import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TVNoise from "@/components/tv-noise";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div
          className="min-h-screen  text-foreground font-sans flex items-center justify-center p-4 md:p-8"
          style={{
            backgroundImage: "url(/images/background.jpg)",
            backgroundSize: "cover",
            backgroundPosition: "center",
          }}
        >
          <TVNoise opacity={1} intensity={0.2} speed={40} />
          <div className="w-full max-w-[900px] z-50 aspect-[1.6/1] bg-[#222] relative p-4 rounded-2xl border border-white/5 overflow-hidden flex shadow-2xl">{children}</div>
        </div>
      </body>
    </html>
  );
}
